keys:
  - &thinkpad age1838zjrhxhnuztfy0x9wn8nkaqh2nplaul3t4mez2r4w5gq5px4js8n7p3w

creation_rules:
  - path_regex: hosts/thinkpad/secrets.ya?ml$
    key_groups:
    - age:
      - *thinkpad

  - path_regex: hosts/common/secrets.ya?ml$
    key_groups:
    - age:
      - *thinkpad
